# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pd92C7lb+6kGQLYZJ2Io47nk4JTmdChrN9sM0FYJZzblu1gnAFF+Th2KnMG4UfFwPGjfLcER2yzoz6TrzWo8fKS/LKHOs/Uz+YyB23InoE6jwPsXUlQQn8aLPjxJH+Mexo1K/3DnG4QLRtmnRrGVWyHMxIoLxxdq8EcmbGFzlnt4OqBiAqvGubBOZiOZZLGk/5kPi+xy5PhOpN5qqGDr/ZxLGOab3TGy0LgShuNMeNDrK+bL9gti5iQE6GQ9+oyApQXbBMFYzaOXCNelbGYFcFoHVV/K1VSVNJtbfgsxG8EVd4+KWISpphnjYrduJSDkIstVvt6mMubxf0oF1PaNj2cmpjPkREq4X1b1GXaXzYrVMvBS7OqXm55Z2DmrPIjPtvj3Ajf8HCSMpAyVw7uah9cPhPv2Tol3vmqMb1oOglPJNs6yjgx2dyhhEtJJCVukKxrnGX0/Y9r2fBMnq/uByFEA2GIYbmaCN4jZmUiazQ88CEzKvp/0Aejib2aMqut5xVn4LwsRNdSSB5wOnwn1ghZ3+aCSfNfP23y7KiB6ocLMd6vpHcM4wb+EK9cjTNjWbiltQVmUYDHliRGRhdpvtnhwA5f3Rz/tCAaDfM0fVTNWAEeJ59DBKz07SXJAP7Mhf569bK123/8SeR4x64awhjGfiquAnlc5sqpf6Fza9AE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
