travis:
  secure:
    BINSTAR_TOKEN: pd92C7lb+6kGQLYZJ2Io47nk4JTmdChrN9sM0FYJZzblu1gnAFF+Th2KnMG4UfFwPGjfLcER2yzoz6TrzWo8fKS/LKHOs/Uz+YyB23InoE6jwPsXUlQQn8aLPjxJH+Mexo1K/3DnG4QLRtmnRrGVWyHMxIoLxxdq8EcmbGFzlnt4OqBiAqvGubBOZiOZZLGk/5kPi+xy5PhOpN5qqGDr/ZxLGOab3TGy0LgShuNMeNDrK+bL9gti5iQE6GQ9+oyApQXbBMFYzaOXCNelbGYFcFoHVV/K1VSVNJtbfgsxG8EVd4+KWISpphnjYrduJSDkIstVvt6mMubxf0oF1PaNj2cmpjPkREq4X1b1GXaXzYrVMvBS7OqXm55Z2DmrPIjPtvj3Ajf8HCSMpAyVw7uah9cPhPv2Tol3vmqMb1oOglPJNs6yjgx2dyhhEtJJCVukKxrnGX0/Y9r2fBMnq/uByFEA2GIYbmaCN4jZmUiazQ88CEzKvp/0Aejib2aMqut5xVn4LwsRNdSSB5wOnwn1ghZ3+aCSfNfP23y7KiB6ocLMd6vpHcM4wb+EK9cjTNjWbiltQVmUYDHliRGRhdpvtnhwA5f3Rz/tCAaDfM0fVTNWAEeJ59DBKz07SXJAP7Mhf569bK123/8SeR4x64awhjGfiquAnlc5sqpf6Fza9AE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
