travis:
  secure:
    BINSTAR_TOKEN: a1zOl5CDtmqmzZQdtVVeYlp01lmiZfSCeNViCRDhHBWYwT9PoI7SNR4zDyb/LzjaYmAYEp2o8AwvDqYnNT8fDRY7Lh2Y4bOS22ddfiHKyDxn6IHY/XzUjB/fCT0mzGPa7u6/pcP3AYEYqDzCbhZ+oGW7zjye5iJoeVqn8Dpln7MxIgjvHCZbMB5tVHE1vEZjgqscx1MU/jqQQQzG78nX8AneEKCK7aozoRHXd09td31x0eVAlTusC13XzJkLoBgjiEWMR0lgJmbAHHi8hz06v3NGfBjlbh1OjTz84S/mqw+bHEFiJigZXAvWRBkWopI6+A4eQ4fM6t32WjpjcKN1PD+MdGKFbUXQqBFnd7sdL0mhW8hFqs1TkVHvOLwTRJJKKAUfxMrMGI+TJdumXmCSCf1hN3ZGULq79XFQSI7cFPVLxj1I8tWHs/7V3WCWpSY2KCub1ehLu6jDbmCzaDiBx4nzfktpDn1URYet1bdlIYKiE5XJ807jdXeg0xT5UwAWgVgCXgISJQCTkQ2whYJEkWYl5wipMiD+J8ZFnSl6++iurFV/TRtSvQROW52ZxEkjRk5qCS6NJq9O2BBOFfne0AfW3VC5S226L3CIbQAD86D/RaUg4CXLZYKE57BJPUM0vuA+HYggzAUe8/RB7T8jatr3yOTmorkbx+5mkVe3WMY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
